services:
  hardware:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    privileged: true
    stdin_open: true
    tty: true
    group_add:
      - dialout
    devices:
      - "${SERIAL_PORT:-/dev/ttyUSB0}:${SERIAL_PORT:-/dev/ttyUSB0}"
    restart: always
    ports:
      - "5000:5000"
    working_dir: /app/src 
    volumes:
      - ../data:/app/data
      - ../src:/app/src
    environment:
      - SERIAL_PORT=${SERIAL_PORT:-/dev/ttyUSB0}
