services:
  hardware:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    privileged: true
    stdin_open: true
    tty: true
    group_add:
      - dialout
    devices:
      - "${SERIAL_PORT:-/dev/ttyUSB0}:${SERIAL_PORT:-/dev/ttyUSB0}"
    restart: always
    ports:
      - "5000:5000"
    working_dir: /app/src 
    volumes:
      - ../data:/app/data
      - ../src:/app/src
    environment:
      - SERIAL_PORT=${SERIAL_PORT:-/dev/ttyUSB0}

  # Panel web para chronit.db
  sqlite-web-chronit:
    image: coleifer/sqlite-web
    container_name: chronit-sqlite-web
    restart: unless-stopped
    ports:
      - "8880:8080"
    volumes:
      - ../data:/data
    environment:
      - SQLITE_DATABASE=chronit.db
    command: sqlite_web --host 0.0.0.0 /data/chronit.db

  # Panel web para users.db
  sqlite-web-users:
    image: coleifer/sqlite-web
    container_name: users-sqlite-web
    restart: unless-stopped
    ports:
      - "8881:8080"
    volumes:
      - ../data:/data
    environment:
      - SQLITE_DATABASE=users.db
    command: sqlite_web --host 0.0.0.0 /data/users.db

  # Panel web para respaldos (puedes cambiar la base de datos desde la interfaz)
  sqlite-web-temp:
    image: coleifer/sqlite-web
    container_name: backups-temp-sqlite-web
    restart: unless-stopped
    ports:
      - "8883:8080"
    volumes:
      - ../data/backups:/data
    environment:
      - SQLITE_DATABASE=_temp_view.db
    command: sqlite_web --host 0.0.0.0 /data/_temp_view.db
